<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'App Payment' => '',
    'Delete Payment' => '',
    'Delete failed.' => '',
    'Delete success.' => '',
    'ID' => '',
    'IP' => '',
    'Jsapi Payment' => '',
    'Manage Payment' => '',
    'Micro Payment' => '',
    'Mweb Payment' => '',
    'Native Payment' => '',
    'Not Pay' => '',
    'Note' => '',
    'Office Payment' => '线下支付',
    'Pay State' => '',
    'Pay Type' => '',
    'State Close' => '',
    'State Error' => '',
    'State Failed' => '',
    'State Not Pay' => '',
    'State Refund' => '',
    'State Revoked' => '',
    'State Success' => '',
    'This id has already been taken' => '该支付已经存在！',
    'Update Payment' => '更新支付',
    'Update success.' => '更新成功',
    'Are you sure you want to delete this item?' => '你确定要删除该项目？',
    'Batch Deletion' => '批量删除',
    'Body' => '交易描述',
    'Create' => '创建',
    'Created At' => '创建时间',
    'Currency' => '币种',
    'Discountable Amount' => '可打折金额',
    'Gateway' => '支付网关',
    'Model Class' => '订单模型',
    'Model ID' => '订单号',
    'Operation' => '操作',
    'Payment' => '付款',
    'Reset' => '重置',
    'Return Url' => '回调URL',
    'Search' => '搜索',
    'Subject' => '订单标题',
    'Total Amount' => '总金额',
    'Trade No' => '支付流水号',
    'Trade State' => '交易状态',
    'Trade Type' => '交易类别',
    'Update' => '更新',
    'Updated At' => '更新时间',
    'User ID' => '用户ID',
];
